var antlr4 = require('antlr4/index');
var NumbersLexer = require('../gen/NumbersLexer');
var NumbersParser = require('../gen/NumbersParser');
var input = "128,100,900,200";
var chars = new antlr4.InputStream(input);
var lexer = new NumbersLexer.NumbersLexer(chars);
var tokens  = new antlr4.CommonTokenStream(lexer);
var parser = new NumbersParser.NumbersParser(tokens);
parser.buildParseTrees = true;
var tree = parser.parse();
console.log("Parsed: "+ tree);
